### ISSUE TITLE
No such file or directory "quaternion_operation/quaternion_operation.h"

### ISSUE THREAD

**Issue by adarsha-s-bharadwaj** [OUXT-Polaris/quaternion_operation#115]
Hello, I'm currently using Linux OS (Ubuntu 22.04) with ROS2 Humble, but whenever I colcon build my workspace, I'm getting this error.

fatal error: quaternion_operation/quaternion_operation.h: No such file or directory
   56 | #include <quaternion_operation/quaternion_operation.h>

Whenever I try to install roscd lite, its saying "Unable to locate package". Can you please tell me how to install roscdlite for ros2 humble or how to install quaternion_operation.h. I request you to please solve this issue for me. Thank you

**Comment by hakuturu583** [comment]
> Whenever I try to install roscd lite, its saying "Unable to locate package". Can you please tell me how to install roscdlite for ros2 humble or how to install quaternion_operation.h. I request you to please solve this issue for me. Thank you

Sorry, I forget to update [README.md](https://github.com/OUXT-Polaris/quaternion_operation/edit/ros2/README.md)...

**Comment by hakuturu583** [comment]
It was documentation for ROS 1.

**Comment by adarsha-s-bharadwaj** [comment]
so we cannot use it for ROS 2 Humble?

**Comment by hakuturu583** [comment]
No, we can use this library with ROS 2.

But the documentation is old.
