### ISSUE TITLE
New release for ROS 2 Rolling

### ISSUE THREAD

**Issue by nuclearsandwich** [OUXT-Polaris/quaternion_operation#60]
The Rolling packages for quaternion_operation are [currently failing](https://build.ros2.org/job/Rbin_uJ64__quaternion_operation__ubuntu_jammy_amd64__binary/123).

https://github.com/OUXT-Polaris/quaternion_operation/pull/58 addresses the immediate issue but has yet to be included in a release targeting ROS 2 Rolling.

**Comment by hakuturu583** [comment]
Thanks!
